### ISSUE TITLE
Parameter Type Validation

### ISSUE THREAD

**Issue by flaviocordova** [moleculer-java/moleculer-java-web#3]
ApiGateway doesn't seem to be able to convert parameters to their expected datatype when calling an action...

For exemple, I have this service:

```javascript
    getAccessCode: {
      params: {
        companyId: { type: 'number' },
      },
      handler(ctx) {
          ....
      }
}
```

and I have mapped the route this way:

```java
route.addAlias("GET", "ckt/getAccessCode/:companyId", "cockpit_auth.getAccessCode");
```

When I request .../getAccessCode/6 it throws a Validation Exception, apparently because it's invoking the service passing a string value, not a number.

if I remove the params definition it works "fine" but it gets a string value.

**Comment by berkesa** [comment]
Hi @flaviocordova!

I talked to @icebob about this problem and he suggested that you **do the conversion on the Node.js side**. It's a good idea to do this because the automatic (caller-side) type conversion would cause other problems (ZIP-code, record ID, phone number, account number conversion to number format, for example "0012 3456" to 123456, etc.).

So instead of this...
```javascript
    getAccessCode: {
        params: {
            companyId: { type: 'number' }
        },
        handler(ctx) {
            ...
        }
    }
```
... do this:
```javascript
    getAccessCode: {
        params: {
            companyId: { type: 'number', convert: true }
        },
        handler(ctx) {
            ...
        }
    }
```
The `convert: true` parameter will automatically convert the `companyId` to numeric form.
